<a href="https://colab.research.google.com/github/ancestor9/2026_Fall_Application-Deployment/blob/main/01_10mins_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import warnings
warnings.filterwarnings('ignore')

# pandas 모듈 import

In [63]:
import pandas as pd
import numpy as np

## csv파일을 불러오기

[실습파일](https://www.data.go.kr/data/15061057/fileData.do)

In [64]:
df = pd.read_csv('/content/주택도시보증공사_전국 신규 민간아파트 분양가격 동향_20260731 (1).csv', encoding='euc-kr')

## 살펴보기

In [65]:
df.head()

  지역명                     규모구분    연도   월 분양가격(제곱미터당 천원)
0  서울                     모든면적  2015  10           5841
1  서울            전용면적 60제곱미터이하  2015  10           5652
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10           5882
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10           5721
4  서울           전용면적 102제곱미터초과  2015  10           5879

In [66]:
df['test'] = True

In [67]:
df.tail()

      지역명                     규모구분    연도  월 분양가격(제곱미터당 천원)  test
11045  제주                     모든면적  2026  7           4473  True
11046  제주            전용면적 60제곱미터이하  2026  7            NaN  True
11047  제주   전용면적 60제곱미터초과 85제곱미터이하  2026  7           4485  True
11048  제주  전용면적 85제곱미터초과 102제곱미터이하  2026  7            NaN  True
11049  제주           전용면적 102제곱미터초과  2026  7           4350  True

## 열의 이름 바꾸기

In [68]:
df=df.rename(columns={'분양가격(제곱미터당 천원)':'분양가'})

In [69]:
df.head()

  지역명                     규모구분    연도   월   분양가  test
0  서울                     모든면적  2015  10  5841  True
1  서울            전용면적 60제곱미터이하  2015  10  5652  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721  True
4  서울           전용면적 102제곱미터초과  2015  10  5879  True

## data type 보기

In [70]:
df.dtypes

지역명     object
규모구분    object
연도       int64
월        int64
분양가     object
test      bool
dtype: object

In [71]:
df.head()

  지역명                     규모구분    연도   월   분양가  test
0  서울                     모든면적  2015  10  5841  True
1  서울            전용면적 60제곱미터이하  2015  10  5652  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721  True
4  서울           전용면적 102제곱미터초과  2015  10  5879  True

In [72]:
df['분양가'] = pd.to_numeric(df['분양가'], errors='coerce')

In [73]:
df.dtypes

지역명      object
규모구분     object
연도        int64
월         int64
분양가     float64
test       bool
dtype: object

In [74]:
df.head()

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

## numpy array로 변환하기

In [75]:
arr = df.to_numpy()

In [76]:
arr

array([['서울', '모든면적', 2015, 10, 5841.0, True],
       ['서울', '전용면적 60제곱미터이하', 2015, 10, 5652.0, True],
       ['서울', '전용면적 60제곱미터초과 85제곱미터이하', 2015, 10, 5882.0, True],
       ...,
       ['제주', '전용면적 60제곱미터초과 85제곱미터이하', 2026, 7, 4485.0, True],
       ['제주', '전용면적 85제곱미터초과 102제곱미터이하', 2026, 7, nan, True],
       ['제주', '전용면적 102제곱미터초과', 2026, 7, 4350.0, True]], dtype=object)

In [77]:
len(arr)

11050

In [78]:
arr[0], arr[1]

(array(['서울', '모든면적', 2015, 10, 5841.0, True], dtype=object),
 array(['서울', '전용면적 60제곱미터이하', 2015, 10, 5652.0, True], dtype=object))

## 간단한 통계 보기

In [79]:
df.describe()

                 연도             월           분양가
count  11050.000000  11050.000000  10049.000000
mean    2020.669231      6.469231   4318.806249
std        3.148740      3.469115   2166.000155
min     2015.000000      1.000000   1868.000000
25%     2018.000000      3.000000   2887.000000
50%     2021.000000      6.000000   3827.000000
75%     2023.000000     10.000000   4957.000000
max     2026.000000     12.000000  22713.000000

## Transposing 하기 (축 변환하기)

In [80]:
# 갯수를 지정하여 출력
df.head(3)

  지역명                    규모구분    연도   월     분양가  test
0  서울                    모든면적  2015  10  5841.0  True
1  서울           전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울  전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True

In [81]:
df.T.head()

,0,1,2,3,4,5,6,7,8,9,...,11040,11041,11042,11043,11044,11045,11046,11047,11048,11049
지역명,서울,서울,서울,서울,서울,인천,인천,인천,인천,인천,...,경남,경남,경남,경남,경남,제주,제주,제주,제주,제주
규모구분,모든면적,전용면적 60제곱미터이하,전용면적 60제곱미터초과 85제곱미터이하,전용면적 85제곱미터초과 102제곱미터이하,전용면적 102제곱미터초과,모든면적,전용면적 60제곱미터이하,전용면적 60제곱미터초과 85제곱미터이하,전용면적 85제곱미터초과 102제곱미터이하,전용면적 102제곱미터초과,...,모든면적,전용면적 60제곱미터이하,전용면적 60제곱미터초과 85제곱미터이하,전용면적 85제곱미터초과 102제곱미터이하,전용면적 102제곱미터초과,모든면적,전용면적 60제곱미터이하,전용면적 60제곱미터초과 85제곱미터이하,전용면적 85제곱미터초과 102제곱미터이하,전용면적 102제곱미터초과
연도,2015,2015,2015,2015,2015,2015,2015,2015,2015,2015,...,2026,2026,2026,2026,2026,2026,2026,2026,2026,2026
월,10,10,10,10,10,10,10,10,10,10,...,7,7,7,7,7,7,7,7,7,7
분양가,5841.0,5652.0,5882.0,5721.0,5879.0,3163.0,3488.0,3119.0,3545.0,3408.0,...,4787.0,4789.0,4767.0,4954.0,5750.0,4473.0,NaN,4485.0,NaN,4350.0

## 정렬

In [82]:
df.head()

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

### 1. Index 정렬

In [83]:
# 내림차순 정렬
df.sort_index(axis=0, ascending=False)[:5]

      지역명                     규모구분    연도  월     분양가  test
11049  제주           전용면적 102제곱미터초과  2026  7  4350.0  True
11048  제주  전용면적 85제곱미터초과 102제곱미터이하  2026  7     NaN  True
11047  제주   전용면적 60제곱미터초과 85제곱미터이하  2026  7  4485.0  True
11046  제주            전용면적 60제곱미터이하  2026  7     NaN  True
11045  제주                     모든면적  2026  7  4473.0  True

In [84]:
# 오름차순 정렬
df.sort_index(axis=0, ascending=True)[:5]

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

### 2. Value 정렬

In [85]:
# 지역명 별로 정렬
df.sort_values(by='지역명')[:5]

      지역명                    규모구분    연도  월     분양가  test
3702   강원  전용면적 60제곱미터초과 85제곱미터이하  2019  5  2489.0  True
10500  강원                    모든면적  2026  1  4603.0  True
10501  강원           전용면적 60제곱미터이하  2026  1  4942.0  True
10502  강원  전용면적 60제곱미터초과 85제곱미터이하  2026  1  4594.0  True
5570   강원                    모든면적  2021  3  2902.0  True

In [86]:
# 연도 별로 정렬
df.sort_values(by='연도')[:5]

   지역명                    규모구분    연도   월     분양가  test
0   서울                    모든면적  2015  10  5841.0  True
1   서울           전용면적 60제곱미터이하  2015  10  5652.0  True
2   서울  전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
51  충북           전용면적 60제곱미터이하  2015  10  1919.0  True
52  충북  전용면적 60제곱미터초과 85제곱미터이하  2015  10  2033.0  True

## 선택 (Selection)

### 1. Column 이름으로 선택

In [87]:
df['지역명'][:5]

0    서울
1    서울
2    서울
3    서울
4    서울
Name: 지역명, dtype: object

In [88]:
df['연도'][:5]

0    2015
1    2015
2    2015
3    2015
4    2015
Name: 연도, dtype: int64

### 2. Index 선택

In [89]:
# index 0 부터 5 미만까지 선택
# index 지정시 : 기준으로 왼쪽은 포함, : 기준으로 오른쪽은 미만
df[0:5]

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

In [90]:
# 끝에 5개 출력
df[-5:]

      지역명                     규모구분    연도  월     분양가  test
11045  제주                     모든면적  2026  7  4473.0  True
11046  제주            전용면적 60제곱미터이하  2026  7     NaN  True
11047  제주   전용면적 60제곱미터초과 85제곱미터이하  2026  7  4485.0  True
11048  제주  전용면적 85제곱미터초과 102제곱미터이하  2026  7     NaN  True
11049  제주           전용면적 102제곱미터초과  2026  7  4350.0  True

### 3. label로 선택

In [91]:
df.loc[:, ['지역명', '연도']][:5]

  지역명    연도
0  서울  2015
1  서울  2015
2  서울  2015
3  서울  2015
4  서울  2015

In [92]:
# (주의) 여기서는 :를 기준으로 우측에 있는 범위인 6을 포함하여 출력
df.loc[:6,['지역명', '연도']]

  지역명    연도
0  서울  2015
1  서울  2015
2  서울  2015
3  서울  2015
4  서울  2015
5  인천  2015
6  인천  2015

In [93]:
# 조건을 삽입 가능
df.loc[df.index > 5, ['지역명', '연도']][:10]

   지역명    연도
6   인천  2015
7   인천  2015
8   인천  2015
9   인천  2015
10  경기  2015
11  경기  2015
12  경기  2015
13  경기  2015
14  경기  2015
15  부산  2015

In [94]:
# 지역명 column의 값이 '인천'인 행의 '지역명', '연도' 출력
df.loc[df['지역명']=='인천',['지역명', '연도']][:10]

   지역명    연도
5   인천  2015
6   인천  2015
7   인천  2015
8   인천  2015
9   인천  2015
90  인천  2015
91  인천  2015
92  인천  2015
93  인천  2015
94  인천  2015

### 4. iloc을 활용한 인덱스 지정 선택

In [95]:
df.head()

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

In [96]:
df.iloc[2, 1]

'전용면적 60제곱미터초과 85제곱미터이하'

In [97]:
# df.iloc과 동작방식은 동일하지만, 범위 지정은 불가
df.iat[2, 1]

'전용면적 60제곱미터초과 85제곱미터이하'

In [98]:
df.iloc[2, :]

지역명                         서울
규모구분    전용면적 60제곱미터초과 85제곱미터이하
연도                        2015
월                           10
분양가                     5882.0
test                      True
Name: 2, dtype: object

In [99]:
df.iloc[:5, 1]

0                       모든면적
1              전용면적 60제곱미터이하
2     전용면적 60제곱미터초과 85제곱미터이하
3    전용면적 85제곱미터초과 102제곱미터이하
4             전용면적 102제곱미터초과
Name: 규모구분, dtype: object

In [100]:
# iloc으로 인덱스 지정시 : 기준으로 왼쪽은 포함, : 기준으로 오른쪽은 미만
df.iloc[:5, 1:3]

                      규모구분    연도
0                     모든면적  2015
1            전용면적 60제곱미터이하  2015
2   전용면적 60제곱미터초과 85제곱미터이하  2015
3  전용면적 85제곱미터초과 102제곱미터이하  2015
4           전용면적 102제곱미터초과  2015

### 5. 범위 조건 지정 선택

In [101]:
df[df.index > 3565]

      지역명                     규모구분    연도  월     분양가  test
3566   제주            전용면적 60제곱미터이하  2019  3  3804.0  True
3567   제주   전용면적 60제곱미터초과 85제곱미터이하  2019  3  3504.0  True
3568   제주  전용면적 85제곱미터초과 102제곱미터이하  2019  3  3226.0  True
3569   제주           전용면적 102제곱미터초과  2019  3  2952.0  True
3570   서울                     모든면적  2019  4  7784.0  True
...    ..                      ...   ... ..     ...   ...
11045  제주                     모든면적  2026  7  4473.0  True
11046  제주            전용면적 60제곱미터이하  2026  7     NaN  True
11047  제주   전용면적 60제곱미터초과 85제곱미터이하  2026  7  4485.0  True
11048  제주  전용면적 85제곱미터초과 102제곱미터이하  2026  7     NaN  True
11049  제주           전용면적 102제곱미터초과  2026  7  4350.0  True

[7484 rows x 6 columns]

### 5-a. df.연도  와  df['연도'] 의 column 지정방식은 동일하다

In [102]:
df[df.연도 == 2019][:5]

     지역명                     규모구분    연도  월     분양가  test
3315  서울                     모든면적  2019  1  7600.0  True
3316  서울            전용면적 60제곱미터이하  2019  1  7400.0  True
3317  서울   전용면적 60제곱미터초과 85제곱미터이하  2019  1  8105.0  True
3318  서울  전용면적 85제곱미터초과 102제곱미터이하  2019  1  6842.0  True
3319  서울           전용면적 102제곱미터초과  2019  1  7787.0  True

In [103]:
df[df['연도'] == 2019][:5]

     지역명                     규모구분    연도  월     분양가  test
3315  서울                     모든면적  2019  1  7600.0  True
3316  서울            전용면적 60제곱미터이하  2019  1  7400.0  True
3317  서울   전용면적 60제곱미터초과 85제곱미터이하  2019  1  8105.0  True
3318  서울  전용면적 85제곱미터초과 102제곱미터이하  2019  1  6842.0  True
3319  서울           전용면적 102제곱미터초과  2019  1  7787.0  True

## Copy로 복사

In [104]:
df.head()

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

In [105]:
copy = df.copy()

In [106]:
copy.head()

  지역명                     규모구분    연도   월     분양가  test
0  서울                     모든면적  2015  10  5841.0  True
1  서울            전용면적 60제곱미터이하  2015  10  5652.0  True
2  서울   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  서울  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  서울           전용면적 102제곱미터초과  2015  10  5879.0  True

## 값 지정

In [107]:
# 지역명 == 서울 인 지역만 선택
df.loc[df['지역명']=='서울','지역명'][:10]

0     서울
1     서울
2     서울
3     서울
4     서울
85    서울
86    서울
87    서울
88    서울
89    서울
Name: 지역명, dtype: object

In [108]:
# 지역명 == 서울 인 지역을 Seoul로 변경(값을 set)
df.loc[df['지역명']=='서울','지역명'] = 'Seoul'

In [109]:
df.head()

     지역명                     규모구분    연도   월     분양가  test
0  Seoul                     모든면적  2015  10  5841.0  True
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True

## reindex를 통한 지정 행과 새로운 열을 추가하여 새로운 dataframe으로 생성

In [110]:
df1 = df.reindex(index=df.index[:7], columns=list(df.columns) + ['extra'])

In [111]:
df1

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True    NaN
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True    NaN
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True    NaN
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True    NaN
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True    NaN
5     인천                     모든면적  2015  10  3163.0  True    NaN
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True    NaN

In [112]:
df1.loc[:4, 'extra'] = False

In [113]:
df1

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False
5     인천                     모든면적  2015  10  3163.0  True    NaN
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True    NaN

## 빈 데이터 처리

In [114]:
df2 = df1.copy()

In [115]:
df2

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False
5     인천                     모든면적  2015  10  3163.0  True    NaN
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True    NaN

### 1. NaN 값이 있는 행을 제거

In [116]:
df2.dropna(how='any')

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False

#### 1-a 하지만 원본 데이터에는 반영이 안되어 있음

In [117]:
df2

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False
5     인천                     모든면적  2015  10  3163.0  True    NaN
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True    NaN

#### 1-b 원본 데이터에 반영을 시키기 위해서는 inplace=True를 적용

In [118]:
df2.dropna(how='any', inplace=True)

In [119]:
# NaN 값이 있는 행이 제거됨
df2

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False

### 2. NaN 값이 있는 행에 값을 채움

In [120]:
df2 = df1.copy()

In [121]:
df2

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False
5     인천                     모든면적  2015  10  3163.0  True    NaN
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True    NaN

In [122]:
df2.fillna(value=True)

     지역명                     규모구분    연도   월     분양가  test  extra
0  Seoul                     모든면적  2015  10  5841.0  True  False
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True  False
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True  False
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True  False
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True  False
5     인천                     모든면적  2015  10  3163.0  True   True
6     인천            전용면적 60제곱미터이하  2015  10  3488.0  True   True

### 3. NaN 값이 있는 데이터를 Boolean 값으로 출력

In [123]:
pd.isna(df2)

     지역명   규모구분     연도      월    분양가   test  extra
0  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False
5  False  False  False  False  False  False   True
6  False  False  False  False  False  False   True

## 연산 (Operation)

In [124]:
df.head()

     지역명                     규모구분    연도   월     분양가  test
0  Seoul                     모든면적  2015  10  5841.0  True
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True

#### 열(column) 기준 평균

In [126]:
df.mean(numeric_only=True)

연도      2020.669231
월          6.469231
분양가     4318.806249
test       1.000000
dtype: float64

#### 행(row) 기준 평균

In [127]:
df.mean(1)[:5]

TypeError: can only concatenate str (not "int") to str

In [128]:
df.head()

     지역명                     규모구분    연도   월     분양가  test
0  Seoul                     모든면적  2015  10  5841.0  True
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True

#### 행을 2칸 뒤로 밀기

In [129]:
df.shift(2)[:5]

     지역명                    규모구분      연도     월     분양가  test
0   None                    None     NaN   NaN     NaN   NaN
1   None                    None     NaN   NaN     NaN   NaN
2  Seoul                    모든면적  2015.0  10.0  5841.0  True
3  Seoul           전용면적 60제곱미터이하  2015.0  10.0  5652.0  True
4  Seoul  전용면적 60제곱미터초과 85제곱미터이하  2015.0  10.0  5882.0  True

#### 행을 2칸 당기기

In [130]:
df.shift(-2)[:5]

     지역명                     규모구분      연도     월     분양가  test
0  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015.0  10.0  5882.0  True
1  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015.0  10.0  5721.0  True
2  Seoul           전용면적 102제곱미터초과  2015.0  10.0  5879.0  True
3     인천                     모든면적  2015.0  10.0  3163.0  True
4     인천            전용면적 60제곱미터이하  2015.0  10.0  3488.0  True

### Broadcasting을 이용한 subtract (빼기)

In [131]:
df1 = df[['연도', '월']]

In [132]:
df1.head()

     연도   월
0  2015  10
1  2015  10
2  2015  10
3  2015  10
4  2015  10

In [133]:
df1.shape

(11050, 2)

In [134]:
s = np.ones(df.shape[0])

In [135]:
s.shape

(11050,)

In [136]:
df1.head()

     연도   월
0  2015  10
1  2015  10
2  2015  10
3  2015  10
4  2015  10

In [137]:
s

array([1., 1., 1., ..., 1., 1., 1.])

In [138]:
df1.sub(s, axis=0).head()

       연도    월
0  2014.0  9.0
1  2014.0  9.0
2  2014.0  9.0
3  2014.0  9.0
4  2014.0  9.0

In [139]:
s = np.ones(df1.shape[1])

In [140]:
s

array([1., 1.])

In [141]:
df1.sub(s, axis=1).head()

       연도    월
0  2014.0  9.0
1  2014.0  9.0
2  2014.0  9.0
3  2014.0  9.0
4  2014.0  9.0

### Apply

np.cumsum : cumulative sum의 함수형으로 누적 합을 구하는 함수

In [142]:
df1.apply(np.cumsum)[:10]

      연도    월
0   2015   10
1   4030   20
2   6045   30
3   8060   40
4  10075   50
5  12090   60
6  14105   70
7  16120   80
8  18135   90
9  20150  100

#### 연도 column
x.max() 는 최대값인 2019년도의 2019
x.min() 은 최소값인 2015년도의 2015
2019 - 2015 = 4가 출력

#### 월 column
x.max() 는 최대값인 12
x.min() 은 최소값인 1
12 - 1 = 11이 출력

In [143]:
df1.apply(lambda x: x.max() - x.min())

연도    11
월     11
dtype: int64

In [144]:
df1.head()

     연도   월
0  2015  10
1  2015  10
2  2015  10
3  2015  10
4  2015  10

## 값들의 종류별 출력

In [145]:
df1['연도'].value_counts()

연도
2016    1020
2017    1020
2018    1020
2019    1020
2023    1020
2020    1020
2021    1020
2022    1020
2025    1020
2024    1020
2026     595
2015     255
Name: count, dtype: int64

## 데이터 합치기 (Data Merge)

In [146]:
df.head()

     지역명                     규모구분    연도   월     분양가  test
0  Seoul                     모든면적  2015  10  5841.0  True
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True

In [147]:
left = df[['연도', '월']]

In [148]:
left.head()

     연도   월
0  2015  10
1  2015  10
2  2015  10
3  2015  10
4  2015  10

In [149]:
right = df[['지역명']]

In [150]:
right.head()

     지역명
0  Seoul
1  Seoul
2  Seoul
3  Seoul
4  Seoul

### 1. Concat

In [151]:
part_1 = pd.DataFrame(np.random.randn(3, 4))
part_2 = pd.DataFrame(np.random.randn(4, 4))
part_3 = pd.DataFrame(np.random.randn(5, 4))

In [152]:
part_1

          0         1         2         3
0 -0.890958 -0.490477 -1.227042  0.416074
1 -1.143341  0.724133 -0.846101 -1.170916
2 -1.048412  0.761684 -0.326057  0.393195

In [153]:
part_2

          0         1         2         3
0  2.362442  0.820441 -2.509102 -0.381970
1 -0.058876 -0.707517  1.034633 -0.907153
2 -0.700817  0.932211  1.080141 -1.131294
3 -1.170388 -0.205899  0.025201  0.246751

In [154]:
part_3

          0         1         2         3
0  0.436526  0.773700 -0.047995  1.477728
1  1.189907  0.818251 -0.870643 -0.652000
2 -0.138286 -1.045006  0.727228  0.972091
3  1.338520  2.336014 -0.643828 -0.136893
4  2.035690 -0.281402  0.152408  1.845705

In [155]:
part = [part_1, part_2, part_3]

In [156]:
part

[          0         1         2         3
 0 -0.890958 -0.490477 -1.227042  0.416074
 1 -1.143341  0.724133 -0.846101 -1.170916
 2 -1.048412  0.761684 -0.326057  0.393195,
           0         1         2         3
 0  2.362442  0.820441 -2.509102 -0.381970
 1 -0.058876 -0.707517  1.034633 -0.907153
 2 -0.700817  0.932211  1.080141 -1.131294
 3 -1.170388 -0.205899  0.025201  0.246751,
           0         1         2         3
 0  0.436526  0.773700 -0.047995  1.477728
 1  1.189907  0.818251 -0.870643 -0.652000
 2 -0.138286 -1.045006  0.727228  0.972091
 3  1.338520  2.336014 -0.643828 -0.136893
 4  2.035690 -0.281402  0.152408  1.845705]

In [157]:
pd.concat(part)

          0         1         2         3
0 -0.890958 -0.490477 -1.227042  0.416074
1 -1.143341  0.724133 -0.846101 -1.170916
2 -1.048412  0.761684 -0.326057  0.393195
0  2.362442  0.820441 -2.509102 -0.381970
1 -0.058876 -0.707517  1.034633 -0.907153
2 -0.700817  0.932211  1.080141 -1.131294
3 -1.170388 -0.205899  0.025201  0.246751
0  0.436526  0.773700 -0.047995  1.477728
1  1.189907  0.818251 -0.870643 -0.652000
2 -0.138286 -1.045006  0.727228  0.972091
3  1.338520  2.336014 -0.643828 -0.136893
4  2.035690 -0.281402  0.152408  1.845705

### 2. Join

Join을 Column(열)을 기준으로 합칠 경우에 on='합치고자하는 열의 이름'를 자주 사용하게 되는데, 값이 고유하지 않다면, 매우 혼란스러울 수 있다

#### 예시1: key가 고유한 경우

In [158]:
left = pd.DataFrame({'연도': ['2015', '2016', '2017', '2018', '2019'], '월': ['1', '2', '3', '4', '5']})
left

     연도  월
0  2015  1
1  2016  2
2  2017  3
3  2018  4
4  2019  5

In [159]:
right = pd.DataFrame({'이름': ['홍길동', '김영희', '이철수', '방탄소년단', 'QUEEN'], '월': ['1', '2', '3', '4', '5']})
right

      이름  월
0    홍길동  1
1    김영희  2
2    이철수  3
3  방탄소년단  4
4  QUEEN  5

In [160]:
left.shape, right.shape

((5, 2), (5, 2))

#### 매우 깔끔하게 합쳐진 것을 볼 수 있다

In [161]:
pd.merge(left, right, on='월')

     연도  월     이름
0  2015  1    홍길동
1  2016  2    김영희
2  2017  3    이철수
3  2018  4  방탄소년단
4  2019  5  QUEEN

#### 예시2: 중복되는 key가 있을 때 합치려는 경우 (1월을 중복으로 넣어놨음)

In [162]:
left = pd.DataFrame({'연도': ['2015', '2016', '2017', '2018', '2019'], '월': ['1', '1', '3', '4', '5']})
left

     연도  월
0  2015  1
1  2016  1
2  2017  3
3  2018  4
4  2019  5

In [163]:
right = pd.DataFrame({'이름': ['홍길동', '김영희', '이철수', '방탄소년단', 'QUEEN'], '월': ['1', '1', '3', '4', '5']})
right

      이름  월
0    홍길동  1
1    김영희  1
2    이철수  3
3  방탄소년단  4
4  QUEEN  5

#### 행이 2개가 더 추가로 합쳐진 모습이다.

In [164]:
pd.merge(left, right, on='월')

     연도  월     이름
0  2015  1    홍길동
1  2015  1    김영희
2  2016  1    홍길동
3  2016  1    김영희
4  2017  3    이철수
5  2018  4  방탄소년단
6  2019  5  QUEEN

### 3. Append

In [165]:
test = np.arange(0, 50)
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [166]:
# 1d -> 2d로 변환
test = test.reshape(10, 5)

In [167]:
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [168]:
test_1 = test[:3]

In [169]:
test_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [170]:
test_2 = test[3:7]

In [171]:
test_2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [172]:
test_3 = test[7:10]

In [173]:
test_3

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [174]:
df1 = pd.DataFrame(test_1)
df1

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [175]:
df2 = pd.DataFrame(test_2)
df2

    0   1   2   3   4
0  15  16  17  18  19
1  20  21  22  23  24
2  25  26  27  28  29
3  30  31  32  33  34

In [176]:
df3 = pd.DataFrame(test_3)
df3

    0   1   2   3   4
0  35  36  37  38  39
1  40  41  42  43  44
2  45  46  47  48  49

In [177]:
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

#### index가 이상하게 출력되는 부분은 ignore_index=True로 해결할 수 있다

In [178]:
df1.append(df2, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

## 그룹화 (Grouping)

In [179]:
df.head()

     지역명                     규모구분    연도   월     분양가  test
0  Seoul                     모든면적  2015  10  5841.0  True
1  Seoul            전용면적 60제곱미터이하  2015  10  5652.0  True
2  Seoul   전용면적 60제곱미터초과 85제곱미터이하  2015  10  5882.0  True
3  Seoul  전용면적 85제곱미터초과 102제곱미터이하  2015  10  5721.0  True
4  Seoul           전용면적 102제곱미터초과  2015  10  5879.0  True

In [180]:
df.shape

(11050, 6)

In [181]:
df.groupby(['지역명', '연도', '월'])['분양가'].agg('sum')

지역명    연도    월
Seoul  2015  10    28975.0
             11    31977.0
             12    31392.0
       2016  1     31635.0
             2     31559.0
                    ...
충북     2026  3     21870.0
             4     22092.0
             5     22178.0
             6     22230.0
             7     18042.0
Name: 분양가, Length: 2210, dtype: float64

#### 분양가 column이 현재 int 타입이 아닌 object 타입으로 되어 있기 때문에 연산이 잘 이뤄지지 않음. 따라서 int 타입으로 변경

In [ ]:
df.info()

In [ ]:
df.info()

In [ ]:
grouped = df.groupby(['지역명', '연도', '월']).sum()
grouped

In [ ]:
grouped.head()

In [ ]:
grouped.stack()

**group이 되어 있는 DataFrame을 unstack의 '레벨'을 조정하여 보여줄 수 있다.**
위의 grouped에서 '도시' = level 1, '연도' = level 2, '월'

In [ ]:
df.head(10)

### stack & unstack을 활용한 column별 데이터 그룹핑

In [ ]:
# level0: 열을 도시별로 출력
grouped.unstack(0)

In [ ]:
# level1: 열을 연도별로 출력
grouped.unstack(1)

In [ ]:
# level2: 열을 연도별로 출력
grouped.unstack(2)

## Pivot Table

#### Pivot Table이란?
다시 말해 피벗 테이블이란 여러 데이터 중에서 자신이 원하는 데이터만을 가지고 원하는 행과 열에 데이터를 배치하여 새로운 보고서를 만드는 기능이다.

In [ ]:
df.head(10)

In [ ]:
pd.pivot_table(df, values='분양가', index=['연도','지역명'], columns=['월'])

## Categoricals

In [ ]:
df.head(10)

In [ ]:
df['분양가'].describe()

In [ ]:
df['평가'] = 0

In [ ]:
df.head(10)

**가격대 별 평가**

low: 25% = 2387 보다 싼 분양가

mid: 50% = 2387 ~ 3130

high: 75% = 3130 ~ 3383

very high: 75% ~ 100% = 3383 보다 비싼 분양가

### np.select를 활용하여 조건에 맞는 값을 대입하기

In [ ]:
conditions = [
    (df['분양가'] < 2387),
    (df['분양가'] >= 2387) & (df['분양가'] < 3130),
    (df['분양가'] >= 3130) & (df['분양가'] < 3383),
    (df['분양가'] >= 3383),
    (df['분양가'] == np.nan)
]
choices = ['저렴', '보통', '비쌈', '매우 비쌈', '-']
df['평가'] = np.select(conditions, choices, default=0)

In [ ]:
df.head(20)

In [ ]:
df.groupby(by='평가').count()

In [ ]:
df.sort_values(by='분양가', ascending=False)[:10]

In [ ]:
df.dtypes

In [ ]:
df['평가'] = df['평가'].astype('category')

In [ ]:
df.dtypes

In [ ]:
df.head(10)

In [ ]:
df['평가'].head()

In [ ]:
df['평가'].cat.categories = ['해당없음', '개비쌈', '평균', '쫌비쌈', '쌈']

In [ ]:
df['평가'].head()