<a href="https://colab.research.google.com/github/ancestor9/2026_Fall_Application-Deployment/blob/main/Tasks/chinook_db_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
DB_URL = "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
DB_PATH = "chinook.db"

In [2]:
import os
import requests

def download_chinook_db():
    if not os.path.exists(DB_PATH):
        print("📥 Downloading Chinook database...")
        response = requests.get(DB_URL)
        with open(DB_PATH, "wb") as f:
            f.write(response.content)
        print("✅ Download complete.")
    else:
        print("✅ Chinook DB already exists.")

download_chinook_db()

📥 Downloading Chinook database...
✅ Download complete.

In [3]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect(DB_PATH)

# Get a list of all tables in the database
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Available tables in the database:", [table[0] for table in tables])
conn.close()

Available tables in the database: ['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

In [4]:
import pandas as pd

# Read data from a table into a pandas DataFrame
# Replace 'albums' with one of the available table names listed above.
query = "SELECT * FROM Album"
df = pd.read_sql_query(query, conn)

# Close the connection
conn.close()

# Display the first few rows of the DataFrame
df

ProgrammingError: Cannot operate on a closed database.

In [5]:
import pandas as pd
import sqlite3

# Re-establish connection to the SQLite database
conn = sqlite3.connect(DB_PATH)

# Read data from a table into a pandas DataFrame
# Replace 'albums' with one of the available table names listed above.
query = "SELECT * FROM Album"
df = pd.read_sql_query(query, conn)

# Close the connection
conn.close()

# Display the first few rows of the DataFrame
df

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [6]:
# @title sqlite3.connect()를 with 구문에 직접 포함
import sqlite3

# Connect to the SQLite database
with sqlite3.connect('chinook.db') as conn:
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    print("Available tables in the database:", [table[0] for table in tables])

Available tables in the database: ['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track']

In [7]:
import sqlite3
import pandas as pd

# Connect to the SQLite database using a 'with' statement
with sqlite3.connect(DB_PATH) as conn:
    # Read data from the 'Album' table into a pandas DataFrame
    query = "SELECT * FROM Album"
    df_album = pd.read_sql_query(query, conn)

# Display the first few rows of the DataFrame
df_album

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [8]:
import sqlite3
import pandas as pd

# Initialize a dictionary to store all DataFrames
dfs = {}

# Connect to the SQLite database using a 'with' statement
with sqlite3.connect(DB_PATH) as conn:
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()

    # Iterate through each table and load it into a DataFrame
    for table_name in [table[0] for table in tables]:
        query = f"SELECT * FROM {table_name}"
        df = pd.read_sql_query(query, conn)
        dfs[table_name] = df
        print(f"--- {table_name} DataFrame head ---")
        display(df.head())
        print("\n")

print("All tables loaded into 'dfs' dictionary.")

--- Album DataFrame head ---

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

--- Artist DataFrame head ---

   ArtistId               Name
0         1              AC/DC
1         2             Accept
2         3          Aerosmith
3         4  Alanis Morissette
4         5    Alice In Chains

--- Customer DataFrame head ---

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

--- Employee DataFrame head ---

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

--- Genre DataFrame head ---

   GenreId                Name
0        1                Rock
1        2                Jazz
2        3               Metal
3        4  Alternative & Punk
4        5       Rock And Roll

--- Invoice DataFrame head ---

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2021-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

--- InvoiceLine DataFrame head ---

   InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              1          1        2       0.99         1
1              2          1        4       0.99         1
2              3          2        6       0.99         1
3              4          2        8       0.99         1
4              5          2       10       0.99         1

--- MediaType DataFrame head ---

   MediaTypeId                         Name
0            1              MPEG audio file
1            2     Protected AAC audio file
2            3  Protected MPEG-4 video file
3            4     Purchased AAC audio file
4            5               AAC audio file

--- Playlist DataFrame head ---

   PlaylistId        Name
0           1       Music
1           2      Movies
2           3    TV Shows
3           4  Audiobooks
4           5  90’s Music

--- PlaylistTrack DataFrame head ---

   PlaylistId  TrackId
0           1     3402
1           1     3389
2           1     3390
3           1     3391
4           1     3392

--- Track DataFrame head ---

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

All tables loaded into 'dfs' dictionary.

In [9]:
dfs.keys()

dict_keys(['Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'MediaType', 'Playlist', 'PlaylistTrack', 'Track'])

In [10]:
dfs['Album']

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [11]:
def summarize_df(df: pd.DataFrame) -> pd.DataFrame:
    # 데이터프레임의 각 컬럼별 데이터 타입, 결측치 수/비율, 대표값 5개를 요약한 DataFrame을 반환합니다.
    summary_data = []
    for col in df.columns:
        dtype = df[col].dtype
        n_unique = df[col].nunique()
        null_cnt = df[col].isnull().sum()
        null_ratio = round((null_cnt / len(df)) * 100, 2)
        unique_vals = df[col].dropna().unique()
        sample_vals = list(unique_vals[:7])

        summary_data.append({
            'Column': col,
            'N_Unique': n_unique,
            'Dtype': dtype,
            'Null_Count': null_cnt,
            'Null_Ratio(%)': null_ratio,
            'Sample_Values_5': sample_vals
        })

    return pd.DataFrame(summary_data)

In [12]:
# Install the xlsxwriter library
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 1.4 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [13]:
output_excel_path = 'all_tables_summary.xlsx'

# Create an Excel writer object
with pd.ExcelWriter(output_excel_path, engine='xlsxwriter') as writer:
    for table_name, df in dfs.items():
        print(f"Summarizing {table_name}...")
        summary_df = summarize_df(df)
        # Write each summary DataFrame to a separate sheet
        summary_df.to_excel(writer, sheet_name=table_name, index=False)
        print(f"Summary for {table_name} written to sheet '{table_name}'.")

print(f"All table summaries saved to '{output_excel_path}'")

Summarizing Album...
Summary for Album written to sheet 'Album'.
Summarizing Artist...
Summary for Artist written to sheet 'Artist'.
Summarizing Customer...
Summary for Customer written to sheet 'Customer'.
Summarizing Employee...
Summary for Employee written to sheet 'Employee'.
Summarizing Genre...
Summary for Genre written to sheet 'Genre'.
Summarizing Invoice...
Summary for Invoice written to sheet 'Invoice'.
Summarizing InvoiceLine...
Summary for InvoiceLine written to sheet 'InvoiceLine'.
Summarizing MediaType...
Summary for MediaType written to sheet 'MediaType'.
Summarizing Playlist...
Summary for Playlist written to sheet 'Playlist'.
Summarizing PlaylistTrack...
Summary for PlaylistTrack written to sheet 'PlaylistTrack'.
Summarizing Track...
Summary for Track written to sheet 'Track'.
All table summaries saved to 'all_tables_summary.xlsx'

In [14]:
from google.colab import files

# Download the generated Excel file
files.download('all_tables_summary.xlsx')

In [15]:
# @title supabase
from google.colab import userdata
SUPABASE_KEY = userdata.get('supakey')

# 접속이 되는 지 사전 확인
import socket
from urllib.parse import urlparse

SUPABASE_URL = "https://qctwuimxnppnzmjcnluc.supabase.co"
hostname = urlparse(SUPABASE_URL).hostname

try:
    ip = socket.gethostbyname(hostname)
    print(f"DNS 조회 성공: {ip}")
except socket.gaierror as e:
    print(f"DNS 조회 실패: {e}")

DNS 조회 성공: 172.64.149.246

In [17]:
!pip install -qU supabase

from supabase.client import create_client, Client

# 수파베이스 공식 파이썬 클라이언트 객체를 생성합니다.
supabase_client: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 1.4 MB/s eta 0:00:00

In [18]:
import sqlite3
import pandas as pd

# 1. SQLite 데이터베이스 연결
conn = sqlite3.connect(DB_PATH)

# 2. 이관할 테이블 목록 및 컬럼 매핑 (외래키 의존성 순서대로 정렬)
# (SQLite 카멜케이스/파스칼케이스 컬럼명을 Supabase의 스네이크케이스 컬럼명으로 전환)
table_mappings = [
    {
        "sqlite_table": "Artist",
        "supabase_table": "artist",
        "columns": {"ArtistId": "artist_id", "Name": "name"}
    },
    {
        "sqlite_table": "Genre",
        "supabase_table": "genre",
        "columns": {"GenreId": "genre_id", "Name": "name"}
    },
    {
        "sqlite_table": "MediaType",
        "supabase_table": "media_type",
        "columns": {"MediaTypeId": "media_type_id", "Name": "name"}
    },
    {
        "sqlite_table": "Album",
        "supabase_table": "album",
        "columns": {"AlbumId": "album_id", "Title": "title", "ArtistId": "artist_id"}
    },
    {
        "sqlite_table": "Track",
        "supabase_table": "track",
        "columns": {
            "TrackId": "track_id", "Name": "name", "AlbumId": "album_id",
            "MediaTypeId": "media_type_id", "GenreId": "genre_id",
            "Composer": "composer", "Milliseconds": "milliseconds",
            "Bytes": "bytes", "UnitPrice": "unit_price"
        }
    },
    {
        "sqlite_table": "Employee",
        "supabase_table": "employee",
        "columns": {
            "EmployeeId": "employee_id", "LastName": "last_name", "FirstName": "first_name",
            "Title": "title", "ReportsTo": "reports_to", "BirthDate": "birth_date",
            "HireDate": "hire_date", "Address": "address", "City": "city",
            "State": "state", "Country": "country", "PostalCode": "postal_code",
            "Phone": "phone", "Fax": "fax", "Email": "email"
        }
    },
    {
        "sqlite_table": "Customer",
        "supabase_table": "customer",
        "columns": {
            "CustomerId": "customer_id", "FirstName": "first_name", "LastName": "last_name",
            "Company": "company", "Address": "address", "City": "city",
            "State": "state", "Country": "country", "PostalCode": "postal_code",
            "Phone": "phone", "Fax": "fax", "Email": "email", "SupportRepId": "support_rep_id"
        }
    },
    {
        "sqlite_table": "Invoice",
        "supabase_table": "invoice",
        "columns": {
            "InvoiceId": "invoice_id", "CustomerId": "customer_id", "InvoiceDate": "invoice_date",
            "BillingAddress": "billing_address", "BillingCity": "billing_city",
            "BillingState": "billing_state", "BillingCountry": "billing_country",
            "BillingPostalCode": "billing_postal_code", "Total": "total"
        }
    },
    {
        "sqlite_table": "InvoiceLine",
        "supabase_table": "invoice_line",
        "columns": {
            "InvoiceLineId": "invoice_line_id", "InvoiceId": "invoice_id",
            "TrackId": "track_id", "UnitPrice": "unit_price", "Quantity": "quantity"
        }
    },
    {
        "sqlite_table": "Playlist",
        "supabase_table": "playlist",
        "columns": {"PlaylistId": "playlist_id", "Name": "name"}
    },
    {
        "sqlite_table": "PlaylistTrack",
        "supabase_table": "playlist_track",
        "columns": {"PlaylistId": "playlist_id", "TrackId": "track_id"}
    }
]

# 3. 데이터 이관 진행
print("🚀 Supabase 데이터 이관을 시작합니다...\n")

BATCH_SIZE = 500  # 청크 단위 업로드 (API 페이로드 제한 방지)

for mapping in table_mappings:
    s_table = mapping["sqlite_table"]
    target_table = mapping["supabase_table"]
    col_map = mapping["columns"]

    # SQLite 데이터 읽기
    df = pd.read_sql_query(f'SELECT * FROM "{s_table}"', conn)

    # 컬럼명 변경 및 NaN(결측치) 처리
    df = df.rename(columns=col_map)
    df = df.where(pd.notnull(df), None)

    records = df.to_dict(orient='records')
    total_records = len(records)

    print(f"📦 [{target_table}] 테이블 이관 중 ({total_records} 개 레코드)...")

    # 배치 분할 업로드
    for i in range(0, total_records, BATCH_SIZE):
        batch = records[i:i + BATCH_SIZE]
        try:
            supabase_client.table(target_table).insert(batch).execute()
        except Exception as e:
            print(f"   ⚠️ 오류 발생 ({target_table}): {e}")
            break

    print(f"   ✅ [{target_table}] 완료\n")

conn.close()
print("🎉 모든 Chinook 데이터베이스 이관이 완료되었습니다!")

🚀 Supabase 데이터 이관을 시작합니다...

📦 [artist] 테이블 이관 중 (275 개 레코드)...
   ✅ [artist] 완료

📦 [genre] 테이블 이관 중 (25 개 레코드)...
   ✅ [genre] 완료

📦 [media_type] 테이블 이관 중 (5 개 레코드)...
   ✅ [media_type] 완료

📦 [album] 테이블 이관 중 (347 개 레코드)...
   ✅ [album] 완료

📦 [track] 테이블 이관 중 (3503 개 레코드)...
   ✅ [track] 완료

📦 [employee] 테이블 이관 중 (8 개 레코드)...
   ⚠️ 오류 발생 (employee): Out of range float values are not JSON compliant: nan
   ✅ [employee] 완료

📦 [customer] 테이블 이관 중 (59 개 레코드)...
   ⚠️ 오류 발생 (customer): {'message': 'insert or update on table "customer" violates foreign key constraint "customer_support_rep_id_fkey"', 'code': '23503', 'hint': None, 'details': 'Key (support_rep_id)=(3) is not present in table "employee".'}
   ✅ [customer] 완료

📦 [invoice] 테이블 이관 중 (412 개 레코드)...
   ⚠️ 오류 발생 (invoice): {'message': 'insert or update on table "invoice" violates foreign key constraint "invoice_customer_id_fkey"', 'code': '23503', 'hint': None, 'details': 'Key (customer_id)=(2) is not present in table "customer".'}
   ✅ [invoice] 완료

📦 [invoice_line] 테이블 이관 중 (2240 개 레코드)...
   ⚠️ 오류 발생 (invoice_line): {'message': 'insert or update on table "invoice_line" violates foreign key constraint "invoice_line_invoice_id_fkey"', 'code': '23503', 'hint': None, 'details': 'Key (invoice_id)=(1) is not present in table "invoice".'}
   ✅ [invoice_line] 완료

📦 [playlist] 테이블 이관 중 (18 개 레코드)...
   ✅ [playlist] 완료

📦 [playlist_track] 테이블 이관 중 (8715 개 레코드)...
   ✅ [playlist_track] 완료

🎉 모든 Chinook 데이터베이스 이관이 완료되었습니다!

- employee 테이블을 넣을 때 발생한 NaN (float) 오류 때문

- employee 테이블의 reports_to 컬럼 등 숫자로 되어 있는 빈 값(Null)이 Pandas에서 NaN (float)으로 처리되어 Supabase JSON 변환 중 에러가 발생

> 이로 인해 employee 데이터가 입력되지 않았고, 이후 customer → invoice → invoice_line 테이블들이 외래키(Foreign Key) 참조 연쇄 오류로 전부 실패한 것

- 해결 방법
Pandas의 where(pd.notnull(df), None) 대신 replace({np.nan: None}) 및 None 변환 로직을 보완하면 깔끔하게 해결

### 모든 테이블을 삭제하고 SQL문장 다시 수행하기

In [20]:
import sqlite3
import pandas as pd
import numpy as np

# 1. SQLite 데이터베이스 연결
conn = sqlite3.connect(DB_PATH)

# 2. 이관할 테이블 목록 및 컬럼 매핑
table_mappings = [
    {
        "sqlite_table": "Artist",
        "supabase_table": "artist",
        "columns": {"ArtistId": "artist_id", "Name": "name"}
    },
    {
        "sqlite_table": "Genre",
        "supabase_table": "genre",
        "columns": {"GenreId": "genre_id", "Name": "name"}
    },
    {
        "sqlite_table": "MediaType",
        "supabase_table": "media_type",
        "columns": {"MediaTypeId": "media_type_id", "Name": "name"}
    },
    {
        "sqlite_table": "Album",
        "supabase_table": "album",
        "columns": {"AlbumId": "album_id", "Title": "title", "ArtistId": "artist_id"}
    },
    {
        "sqlite_table": "Track",
        "supabase_table": "track",
        "columns": {
            "TrackId": "track_id", "Name": "name", "AlbumId": "album_id",
            "MediaTypeId": "media_type_id", "GenreId": "genre_id",
            "Composer": "composer", "Milliseconds": "milliseconds",
            "Bytes": "bytes", "UnitPrice": "unit_price"
        }
    },
    {
        "sqlite_table": "Employee",
        "supabase_table": "employee",
        "columns": {
            "EmployeeId": "employee_id", "LastName": "last_name", "FirstName": "first_name",
            "Title": "title", "ReportsTo": "reports_to", "BirthDate": "birth_date",
            "HireDate": "hire_date", "Address": "address", "City": "city",
            "State": "state", "Country": "country", "PostalCode": "postal_code",
            "Phone": "phone", "Fax": "fax", "Email": "email"
        }
    },
    {
        "sqlite_table": "Customer",
        "supabase_table": "customer",
        "columns": {
            "CustomerId": "customer_id", "FirstName": "first_name", "LastName": "last_name",
            "Company": "company", "Address": "address", "City": "city",
            "State": "state", "Country": "country", "PostalCode": "postal_code",
            "Phone": "phone", "Fax": "fax", "Email": "email", "SupportRepId": "support_rep_id"
        }
    },
    {
        "sqlite_table": "Invoice",
        "supabase_table": "invoice",
        "columns": {
            "InvoiceId": "invoice_id", "CustomerId": "customer_id", "InvoiceDate": "invoice_date",
            "BillingAddress": "billing_address", "BillingCity": "billing_city",
            "BillingState": "billing_state", "BillingCountry": "billing_country",
            "BillingPostalCode": "billing_postal_code", "Total": "total"
        }
    },
    {
        "sqlite_table": "InvoiceLine",
        "supabase_table": "invoice_line",
        "columns": {
            "InvoiceLineId": "invoice_line_id", "InvoiceId": "invoice_id",
            "TrackId": "track_id", "UnitPrice": "unit_price", "Quantity": "quantity"
        }
    },
    {
        "sqlite_table": "Playlist",
        "supabase_table": "playlist",
        "columns": {"PlaylistId": "playlist_id", "Name": "name"}
    },
    {
        "sqlite_table": "PlaylistTrack",
        "supabase_table": "playlist_track",
        "columns": {"PlaylistId": "playlist_id", "TrackId": "track_id"}
    }
]

# 3. 데이터 이관 진행
print("🚀 Supabase 데이터 이관을 시작합니다...\n")

BATCH_SIZE = 500

for mapping in table_mappings:
    s_table = mapping["sqlite_table"]
    target_table = mapping["supabase_table"]
    col_map = mapping["columns"]

    # SQLite 데이터 읽기
    df = pd.read_sql_query(f'SELECT * FROM "{s_table}"', conn)

    # 컬럼명 변경
    df = df.rename(columns=col_map)

    # NaN/NaT 값을 Python None(JSON null)으로 완벽하게 변환하는 부분
    df = df.replace({np.nan: None})
    records = df.to_dict(orient='records')

    # dict 요소 중 float NaN 또는 NaT를 한번 더 체크하여 None 처리
    clean_records = []
    for record in records:
        clean_record = {
            k: (None if pd.isna(v) else int(v) if isinstance(v, float) and v.is_integer() else v)
            for k, v in record.items()
        }
        clean_records.append(clean_record)

    total_records = len(clean_records)
    print(f"📦 [{target_table}] 테이블 이관 중 ({total_records} 개 레코드)...")

    # 배치 분할 업로드
    success = True
    for i in range(0, total_records, BATCH_SIZE):
        batch = clean_records[i:i + BATCH_SIZE]
        try:
            supabase_client.table(target_table).insert(batch).execute()
        except Exception as e:
            print(f"   ⚠️ 오류 발생 ({target_table}): {e}")
            success = False
            break

    if success:
        print(f"   ✅ [{target_table}] 성공\n")

conn.close()
print("🎉 모든 Chinook 데이터베이스 이관이 완벽히 완료되었습니다!")

🚀 Supabase 데이터 이관을 시작합니다...

📦 [artist] 테이블 이관 중 (275 개 레코드)...
   ✅ [artist] 성공

📦 [genre] 테이블 이관 중 (25 개 레코드)...
   ✅ [genre] 성공

📦 [media_type] 테이블 이관 중 (5 개 레코드)...
   ✅ [media_type] 성공

📦 [album] 테이블 이관 중 (347 개 레코드)...
   ✅ [album] 성공

📦 [track] 테이블 이관 중 (3503 개 레코드)...
   ✅ [track] 성공

📦 [employee] 테이블 이관 중 (8 개 레코드)...
   ✅ [employee] 성공

📦 [customer] 테이블 이관 중 (59 개 레코드)...
   ✅ [customer] 성공

📦 [invoice] 테이블 이관 중 (412 개 레코드)...
   ✅ [invoice] 성공

📦 [invoice_line] 테이블 이관 중 (2240 개 레코드)...
   ✅ [invoice_line] 성공

📦 [playlist] 테이블 이관 중 (18 개 레코드)...
   ✅ [playlist] 성공

📦 [playlist_track] 테이블 이관 중 (8715 개 레코드)...
   ✅ [playlist_track] 성공

🎉 모든 Chinook 데이터베이스 이관이 완벽히 완료되었습니다!