<a href="https://colab.research.google.com/github/ancestor9/2026_Fall_Application-Deployment/blob/main/20261106/ch13_2_MovieLens_1M_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.random import randn
import numpy as np
np.random.seed(123)
import os
import matplotlib.pyplot as plt
import pandas as pd
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4)
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **13.2 MovieLens 1M Dataset**

In [ ]:
path ="/content/drive/MyDrive/2026_Fall_Python for Data Science/"

In [ ]:
path + "datasets/movielens/users.dat"

'/content/drive/MyDrive/2026_Fall_Python for Data Science/datasets/movielens/users.dat'

In [ ]:
unames = ["user_id", "gender", "age", "occupation", "zip"]
users = pd.read_table(f'{path}datasets/movielens/users.dat', sep="::",
                      header=None, names=unames, engine="python")
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [ ]:
rnames = ["user_id", "movie_id", "rating", "timestamp"]
ratings = pd.read_table(f'{path}datasets/movielens/ratings.dat', sep="::",
                        header=None, names=rnames, engine="python")

# 전체 데이터 중 10%만 무작위로 추출하여 ratings 변수에 재할당
ratings = ratings.sample(frac=0.05, random_state=42)
ratings

        user_id  movie_id  rating  timestamp
895536     5412      2683       2  960243649
899739     5440       904       5  959995181
55687       368      3717       4  976311423
63727       425      1721       4  976283587
822011     4942      3697       1  962642480
...         ...       ...     ...        ...
293576     1748       930       4  974725343
8813         59      2728       3  977933606
687511     4115      3251       2  965365925
831184     4995       176       4  968297975
882062     5329      2485       4  960917096

[50010 rows x 4 columns]

In [ ]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table(f'{path}datasets/movielens/movies.dat', sep="::",
                       header=None, names=mnames, engine="python")
# 전체 데이터 중 10%만 무작위로 추출하여 ratings 변수에 재할당
movies = movies.sample(frac=0.05, random_state=42)
movies

,movie_id,title,genres
1344,1365,Ridicule (1996),Drama
2637,2706,American Pie (1999),Comedy
3598,3667,Rent-A-Cop (1988),Action|Comedy
3615,3684,"Fabulous Baker Boys, The (1989)",Drama|Romance
1812,1881,Quest for Camelot (1998),Adventure|Animation|Children's|Fantasy
...,...,...,...
2222,2291,Edward Scissorhands (1990),Drama|Romance
2805,2874,"Pajama Game, The (1957)",Comedy
1517,1556,Speed 2: Cruise Control (1997),Action|Romance|Thriller
109,111,Taxi Driver (1976),Drama|Thriller
903,915,Sabrina (1954),Comedy|Romance

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
users.head(5)
ratings.head(5)
movies.head(5)

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

        user_id  movie_id  rating  timestamp
895536     5412      2683       2  960243649
899739     5440       904       5  959995181
55687       368      3717       4  976311423
63727       425      1721       4  976283587
822011     4942      3697       1  962642480

,movie_id,title,genres
1344,1365,Ridicule (1996),Drama
2637,2706,American Pie (1999),Comedy
3598,3667,Rent-A-Cop (1988),Action|Comedy
3615,3684,"Fabulous Baker Boys, The (1989)",Drama|Romance
1812,1881,Quest for Camelot (1998),Adventure|Animation|Children's|Fantasy

In [ ]:
# @title **3개 파일을 정리하여 데이터를 파악하는 코드**

def summarize_dataframe(df, df_name):
    print(f"\n--- Summary for DataFrame: {df_name} ---")
    summary = pd.DataFrame(index=df.columns)
    summary["Data Type"] = df.dtypes
    summary["Unique Values"] = df.nunique()
    summary["Missing Values (%)"] = df.isnull().sum() * 100 / len(df)

    top_values_list = []
    for col in df.columns:
        if df[col].nunique() > 0:
            top_5_values = df[col].value_counts().nlargest(5).to_dict()
            top_values_list.append(str(top_5_values))
        else:
            top_values_list.append("N/A")

    summary["Top 5 Values"] = top_values_list

    # Convert float columns to two decimal places where appropriate
    for col in ["Missing Values (%)"]:
        if col in summary.columns:
            summary[col] = summary[col].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")

    display(summary)

# Apply the function to the specified DataFrames
summarize_dataframe(users, "users")
summarize_dataframe(ratings, "ratings")
summarize_dataframe(movies, "movies")

--- Summary for DataFrame: users ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,6040,0.00,"{6040: 1, 1: 1, 2: 1, 3: 1, 4: 1}"
gender,object,2,0.00,"{'M': 4331, 'F': 1709}"
age,int64,7,0.00,"{25: 2096, 35: 1193, 18: 1103, 45: 550, 50: 496}"
occupation,int64,21,0.00,"{4: 759, 0: 711, 7: 679, 1: 528, 17: 502}"
zip,object,3439,0.00,"{'48104': 19, '22903': 18, '55104': 17, '94110': 17, '10025': 16}"

--- Summary for DataFrame: ratings ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,5620,0.00,"{4169: 130, 1680: 84, 889: 84, 1181: 80, 2909: 77}"
movie_id,int64,3098,0.00,"{2858: 167, 1210: 157, 2571: 149, 110: 140, 1580: 140}"
rating,int64,5,0.00,"{4: 17518, 3: 13049, 5: 11333, 2: 5248, 1: 2862}"
timestamp,int64,47245,0.00,"{974697405: 4, 974770379: 4, 971639954: 4, 965337444: 4, 975280390: 4}"

--- Summary for DataFrame: movies ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
movie_id,int64,194,0.00,"{1365: 1, 2706: 1, 3667: 1, 3684: 1, 1881: 1}"
title,object,194,0.00,"{'Ridicule (1996)': 1, 'American Pie (1999)': 1, 'Rent-A-Cop (1988)': 1, 'Fa..."
genres,object,67,0.00,"{'Drama': 38, 'Comedy': 29, 'Horror': 12, 'Comedy|Drama': 10, 'Comedy|Romanc..."

In [ ]:
data = pd.merge(pd.merge(ratings, users), movies)
data
data.iloc[0]

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,3272,1518,4,971247428,M,35,0,08330,Breakdown (1997),Action|Thriller
1,4509,2706,4,964981140,M,25,7,38261,American Pie (1999),Comedy
2,3995,318,5,965583912,M,35,17,22810,"Shawshank Redemption, The (1994)",Drama
3,3391,924,5,967586889,M,18,4,48135,2001: A Space Odyssey (1968),Drama|Mystery|Sci-Fi|Thriller
4,4416,1196,5,965323896,M,18,4,02134,Star Wars: Episode V - The Empire Strikes Back (1980),Action|Adventure|Drama|Sci-Fi|War
...,...,...,...,...,...,...,...,...,...,...
2459,1850,1881,4,974697866,M,18,5,12582,Quest for Camelot (1998),Adventure|Animation|Children's|Fantasy
2460,1175,2291,4,974857637,F,25,2,90020,Edward Scissorhands (1990),Drama|Romance
2461,5947,1240,4,957190753,F,45,16,97215,"Terminator, The (1984)",Action|Sci-Fi|Thriller
2462,3404,648,4,967425854,M,25,8,95380,Mission: Impossible (1996),Action|Adventure|Mystery
2463,2540,329,4,974047630,F,45,6,42420,Star Trek: Generations (1994),Action|Adventure|Sci-Fi

user_id                   3272
movie_id                  1518
rating                       4
timestamp            971247428
gender                       M
age                         35
occupation                   0
zip                      08330
title         Breakdown (1997)
genres         Action|Thriller
Name: 0, dtype: object

In [ ]:
summarize_dataframe(data, 'data')

--- Summary for DataFrame: data ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,1714,0.00,"{4169: 10, 1019: 9, 1447: 7, 549: 6, 1980: 6}"
movie_id,int64,157,0.00,"{1196: 135, 318: 109, 1240: 93, 924: 87, 2291: 85}"
rating,int64,5,0.00,"{4: 833, 3: 629, 5: 595, 2: 271, 1: 136}"
timestamp,int64,2457,0.00,"{960086837: 2, 971368640: 2, 965154882: 2, 971580814: 2, 965337444: 2}"
gender,object,2,0.00,"{'M': 1867, 'F': 597}"
age,int64,7,0.00,"{25: 925, 35: 524, 18: 436, 45: 208, 50: 207}"
occupation,int64,21,0.00,"{0: 325, 4: 308, 7: 268, 1: 225, 17: 180}"
zip,object,1312,0.00,"{'98103': 15, '22903': 13, '60640': 13, '66048': 12, '48135': 10}"
title,object,157,0.00,"{'Star Wars: Episode V - The Empire Strikes Back (1980)': 135, 'Shawshank Re..."
genres,object,62,0.00,"{'Drama': 381, 'Comedy': 305, 'Action|Adventure|Drama|Sci-Fi|War': 135, 'Dra..."

In [ ]:
mean_ratings = data.pivot_table("rating", index="title",
                                columns="gender", aggfunc="mean")
mean_ratings.head(5)

gender                               F         M
title
12 Angry Men (1957)           3.833333  4.250000
2001: A Space Odyssey (1968)  3.800000  4.313433
54 (1998)                     2.500000  2.727273
Age of Innocence, The (1993)  4.000000  3.230769
Air Up There, The (1994)      1.666667  2.900000

In [ ]:
ratings_by_title = data.groupby("title").size()
ratings_by_title.head()
active_titles = ratings_by_title.index[ratings_by_title >= 250]
active_titles

title
12 Angry Men (1957)             26
2001: A Space Odyssey (1968)    87
54 (1998)                       13
Age of Innocence, The (1993)    18
Air Up There, The (1994)        13
dtype: int64

Index([], dtype='object', name='title')

In [ ]:
mean_ratings = mean_ratings.loc[active_titles]
mean_ratings

Empty DataFrame
Columns: [F, M]
Index: []

In [ ]:
mean_ratings = mean_ratings.rename(index={"Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954)":
                           "Seven Samurai (Shichinin no samurai) (1954)"})

mean_ratings

Empty DataFrame
Columns: [F, M]
Index: []

In [ ]:
top_female_ratings = mean_ratings.sort_values("F", ascending=False)
top_female_ratings.head()

Empty DataFrame
Columns: [F, M]
Index: []

In [ ]:
mean_ratings["diff"] = mean_ratings["M"] - mean_ratings["F"]

In [ ]:
sorted_by_diff = mean_ratings.sort_values("diff")
sorted_by_diff.head()

Empty DataFrame
Columns: [F, M, diff]
Index: []

In [ ]:
sorted_by_diff[::-1].head()

Empty DataFrame
Columns: [F, M, diff]
Index: []

In [ ]:
rating_std_by_title = data.groupby("title")["rating"].std()
rating_std_by_title = rating_std_by_title.loc[active_titles]
rating_std_by_title.head()

Series([], Name: rating, dtype: float64)

In [ ]:
rating_std_by_title.sort_values(ascending=False)[:10]

Series([], Name: rating, dtype: float64)

In [ ]:
movies["genres"].head()
movies["genres"].head().str.split("|")
movies["genre"] = movies.pop("genres").str.split("|")
movies.head()

1344                                     Drama
2637                                    Comedy
3598                             Action|Comedy
3615                             Drama|Romance
1812    Adventure|Animation|Children's|Fantasy
Name: genres, dtype: object

1344                                        [Drama]
2637                                       [Comedy]
3598                               [Action, Comedy]
3615                               [Drama, Romance]
1812    [Adventure, Animation, Children's, Fantasy]
Name: genres, dtype: object

,movie_id,title,genre
1344,1365,Ridicule (1996),[Drama]
2637,2706,American Pie (1999),[Comedy]
3598,3667,Rent-A-Cop (1988),"[Action, Comedy]"
3615,3684,"Fabulous Baker Boys, The (1989)","[Drama, Romance]"
1812,1881,Quest for Camelot (1998),"[Adventure, Animation, Children's, Fantasy]"

In [ ]:
movies_exploded = movies.explode("genre")
movies_exploded[:10]

      movie_id                            title       genre
1344      1365                  Ridicule (1996)       Drama
2637      2706              American Pie (1999)      Comedy
3598      3667                Rent-A-Cop (1988)      Action
3598      3667                Rent-A-Cop (1988)      Comedy
3615      3684  Fabulous Baker Boys, The (1989)       Drama
3615      3684  Fabulous Baker Boys, The (1989)     Romance
1812      1881         Quest for Camelot (1998)   Adventure
1812      1881         Quest for Camelot (1998)   Animation
1812      1881         Quest for Camelot (1998)  Children's
1812      1881         Quest for Camelot (1998)     Fantasy

In [ ]:
# @title **모든 장르를 컬럼으로하고 해당이 되면 0 아니면 1로 값을 입력하는 코드**

genres_one_hot = pd.get_dummies(movies_exploded['genre'], prefix='genre')
movies_with_genres = movies_exploded[['movie_id', 'title']].drop_duplicates().set_index('movie_id')

# Merge the one-hot encoded genres with movie_id and title
movies_genres_encoded = pd.merge(movies_exploded[['movie_id', 'title']], genres_one_hot, left_index=True, right_index=True)

# Group by movie_id and title, then sum the genre columns to handle movies with multiple genres
final_movies_genres = movies_genres_encoded.groupby(['movie_id', 'title']).sum().reset_index()

# Convert sums greater than 1 to 1 for true binary representation (though get_dummies + sum should result in 0 or 1 if genre is unique per row)
# In case a movie had the same genre listed multiple times, this step ensures it's still 1.
for col in final_movies_genres.columns:
    if col.startswith('genre_'):
        final_movies_genres[col] = (final_movies_genres[col] > 0).astype(int)

final_movies_genres.head()

,movie_id,title,genre_Action,genre_Adventure,genre_Animation,genre_Children's,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Fantasy,genre_Film-Noir,genre_Horror,genre_Musical,genre_Mystery,genre_Romance,genre_Sci-Fi,genre_Thriller,genre_War,genre_Western
0,9,Sudden Death (1995),1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,15,Cutthroat Island (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,18,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,33,Wings of Courage (1995),0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,71,Fair Game (1995),1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
ratings_with_genre = pd.merge(pd.merge(movies_exploded, ratings), users)
ratings_with_genre.iloc[0]
genre_ratings = (ratings_with_genre.groupby(["genre", "age"])
                 ["rating"].mean()
                 .unstack("age"))
genre_ratings[:10]

movie_id                 1365
title         Ridicule (1996)
genre                   Drama
user_id                   531
rating                      3
timestamp           978972689
gender                      F
age                        18
occupation                 14
zip                     22206
Name: 0, dtype: object

age,1,18,25,35,45,50,56
genre,,,,,,,
Action,3.789474,3.514085,3.582043,3.623288,3.700000,3.587302,3.354839
Adventure,3.916667,3.647887,3.606936,3.574713,3.793103,3.767442,3.750000
Animation,3.400000,3.380952,3.482759,3.608696,3.500000,3.333333,3.000000
Children's,3.000000,3.310345,2.931818,3.228571,3.200000,3.000000,3.250000
Comedy,3.720000,3.365854,3.320144,3.491429,3.535714,3.729167,3.677419
Crime,NaN,3.360000,3.036364,3.407407,3.800000,3.000000,3.571429
Documentary,NaN,NaN,NaN,NaN,3.000000,NaN,NaN
Drama,4.000000,3.846890,3.844037,3.908046,4.050847,3.950413,3.897959
Fantasy,NaN,3.333333,2.833333,4.000000,NaN,3.500000,NaN
Film-Noir,NaN,NaN,4.000000,NaN,3.000000,NaN,NaN