<a href="https://colab.research.google.com/github/ancestor9/2026_Fall_Application-Deployment/blob/main/20261106/ch13_2_MovieLens_1M_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.random import randn
import numpy as np
np.random.seed(123)
import os
import matplotlib.pyplot as plt
import pandas as pd
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4)
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80

## **13.2 MovieLens 1M Dataset**

In [ ]:
import requests

# GitHub API Endpoint 주소
url = "https://api.github.com/repos/wesm/pydata-book/contents/datasets/movielens?ref=3rd-edition"

response = requests.get(url)

if response.status_code == 200:
    files = response.json()
    for file in files:
        print(file['name']) # 파일 이름 출력
else:
    print(f"Error: {response.status_code}")

README
movies.dat
ratings.dat
users.dat

In [ ]:
import pandas as pd

# GitHub Raw 데이터 주소로 경로를 지정
raw_path = "https://raw.githubusercontent.com/wesm/pydata-book/3rd-edition/"

unames = ["user_id", "gender", "age", "occupation", "zip"]
users = pd.read_csv(
    f"{raw_path}datasets/movielens/users.dat",
    sep="::",
    header=None,
    names=unames,
    engine="python",
)
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
...       ...    ...  ...         ...    ...
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [ ]:
rnames = ["user_id", "movie_id", "rating", "timestamp"]
ratings = pd.read_csv(
    f"{raw_path}datasets/movielens/ratings.dat",
    sep="::",
    header=None,
    names=rnames,
    engine="python",
)
ratings

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
...          ...       ...     ...        ...
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [ ]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_csv(
    f"{raw_path}datasets/movielens/movies.dat",
    sep="::",
    header=None,
    names=mnames,
    engine="python",
)
movies

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
users.head(5)
ratings.head(5)
movies.head(5)

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
# @title **3개 파일을 정리하여 데이터를 파악하는 코드**

def summarize_dataframe(df, df_name):
    print(f"\n--- Summary for DataFrame: {df_name} ---")
    summary = pd.DataFrame(index=df.columns)
    summary["Data Type"] = df.dtypes
    summary["Unique Values"] = df.nunique()
    summary["Missing Values (%)"] = df.isnull().sum() * 100 / len(df)

    top_values_list = []
    for col in df.columns:
        if df[col].nunique() > 0:
            top_5_values = df[col].value_counts().nlargest(5).to_dict()
            top_values_list.append(str(top_5_values))
        else:
            top_values_list.append("N/A")

    summary["Top 5 Values"] = top_values_list

    # Convert float columns to two decimal places where appropriate
    for col in ["Missing Values (%)"]:
        if col in summary.columns:
            summary[col] = summary[col].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")

    display(summary)

# Apply the function to the specified DataFrames
summarize_dataframe(users, "users")
summarize_dataframe(ratings, "ratings")
summarize_dataframe(movies, "movies")

--- Summary for DataFrame: users ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,6040,0.00,"{6040: 1, 1: 1, 2: 1, 3: 1, 4: 1}"
gender,object,2,0.00,"{'M': 4331, 'F': 1709}"
age,int64,7,0.00,"{25: 2096, 35: 1193, 18: 1103, 45: 550, 50: 496}"
occupation,int64,21,0.00,"{4: 759, 0: 711, 7: 679, 1: 528, 17: 502}"
zip,object,3439,0.00,"{'48104': 19, '22903': 18, '55104': 17, '94110': 17, '10025': 16}"

--- Summary for DataFrame: ratings ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,6040,0.00,"{4169: 2314, 1680: 1850, 4277: 1743, 1941: 1595, 1181: 1521}"
movie_id,int64,3706,0.00,"{2858: 3428, 260: 2991, 1196: 2990, 1210: 2883, 480: 2672}"
rating,int64,5,0.00,"{4: 348971, 3: 261197, 5: 226310, 2: 107557, 1: 56174}"
timestamp,int64,458455,0.00,"{975528402: 30, 975440712: 28, 975527781: 28, 975528243: 27, 1025585635: 27}"

--- Summary for DataFrame: movies ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
movie_id,int64,3883,0.00,"{3952: 1, 1: 1, 2: 1, 3: 1, 4: 1}"
title,object,3883,0.00,"{'Contender, The (2000)': 1, 'Toy Story (1995)': 1, 'Jumanji (1995)': 1, 'Gr..."
genres,object,301,0.00,"{'Drama': 843, 'Comedy': 521, 'Horror': 178, 'Comedy|Drama': 162, 'Comedy|Ro..."

In [ ]:
data = pd.merge(pd.merge(ratings, users), movies)
data
data.iloc[0]

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000204,6040,1091,1,956716541,M,25,6,11106,Weekend at Bernie's (1989),Comedy
1000205,6040,1094,5,956704887,M,25,6,11106,"Crying Game, The (1992)",Drama|Romance|War
1000206,6040,562,5,956704746,M,25,6,11106,Welcome to the Dollhouse (1995),Comedy|Drama
1000207,6040,1096,4,956715648,M,25,6,11106,Sophie's Choice (1982),Drama
1000208,6040,1097,4,956715569,M,25,6,11106,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
zip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [ ]:
summarize_dataframe(data, 'data')

--- Summary for DataFrame: data ---

,Data Type,Unique Values,Missing Values (%),Top 5 Values
user_id,int64,6040,0.00,"{4169: 2314, 1680: 1850, 4277: 1743, 1941: 1595, 1181: 1521}"
movie_id,int64,3706,0.00,"{2858: 3428, 260: 2991, 1196: 2990, 1210: 2883, 480: 2672}"
rating,int64,5,0.00,"{4: 348971, 3: 261197, 5: 226310, 2: 107557, 1: 56174}"
timestamp,int64,458455,0.00,"{975528402: 30, 975440712: 28, 975527781: 28, 975528243: 27, 1025585635: 27}"
gender,object,2,0.00,"{'M': 753769, 'F': 246440}"
age,int64,7,0.00,"{25: 395556, 35: 199003, 18: 183536, 45: 83633, 50: 72490}"
occupation,int64,21,0.00,"{4: 131032, 0: 130499, 7: 105425, 1: 85351, 17: 72816}"
zip,object,3439,0.00,"{'94110': 3802, '60640': 3430, '98103': 3204, '95616': 3079, '02138': 3019}"
title,object,3706,0.00,"{'American Beauty (1999)': 3428, 'Star Wars: Episode IV - A New Hope (1977)'..."
genres,object,301,0.00,"{'Comedy': 116883, 'Drama': 111423, 'Comedy|Romance': 42712, 'Comedy|Drama':..."

In [ ]:
mean_ratings = data.pivot_table("rating", index="title",
                                columns="gender", aggfunc="mean")
mean_ratings.head(5)

gender                                F         M
title
$1,000,000 Duck (1971)         3.375000  2.761905
'Night Mother (1986)           3.388889  3.352941
'Til There Was You (1997)      2.675676  2.733333
'burbs, The (1989)             2.793478  2.962085
...And Justice for All (1979)  3.828571  3.689024

In [ ]:
ratings_by_title = data.groupby("title").size()
ratings_by_title.head()
active_titles = ratings_by_title.index[ratings_by_title >= 250]
active_titles

title
$1,000,000 Duck (1971)            37
'Night Mother (1986)              70
'Til There Was You (1997)         52
'burbs, The (1989)               303
...And Justice for All (1979)    199
dtype: int64

Index([''burbs, The (1989)', '10 Things I Hate About You (1999)',
       '101 Dalmatians (1961)', '101 Dalmatians (1996)', '12 Angry Men (1957)',
       '13th Warrior, The (1999)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '2010 (1984)',
       ...
       'X-Men (2000)', 'Year of Living Dangerously (1982)',
       'Yellow Submarine (1968)', 'You've Got Mail (1998)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Sherlock Holmes (1985)',
       'Zero Effect (1998)', 'eXistenZ (1999)'],
      dtype='object', name='title', length=1216)

In [ ]:
mean_ratings = mean_ratings.loc[active_titles]
mean_ratings

gender                                    F         M
title
'burbs, The (1989)                 2.793478  2.962085
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421
...                                     ...       ...
Young Guns (1988)                  3.371795  3.425620
Young Guns II (1990)               2.934783  2.904025
Young Sherlock Holmes (1985)       3.514706  3.363344
Zero Effect (1998)                 3.864407  3.723140
eXistenZ (1999)                    3.098592  3.289086

[1216 rows x 2 columns]

In [ ]:
mean_ratings = mean_ratings.rename(index={"Seven Samurai (The Magnificent Seven) (Shichinin no samurai) (1954)":
                           "Seven Samurai (Shichinin no samurai) (1954)"})

mean_ratings

gender                                    F         M
title
'burbs, The (1989)                 2.793478  2.962085
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421
...                                     ...       ...
Young Guns (1988)                  3.371795  3.425620
Young Guns II (1990)               2.934783  2.904025
Young Sherlock Holmes (1985)       3.514706  3.363344
Zero Effect (1998)                 3.864407  3.723140
eXistenZ (1999)                    3.098592  3.289086

[1216 rows x 2 columns]

In [ ]:
top_female_ratings = mean_ratings.sort_values("F", ascending=False)
top_female_ratings.head()

gender                                                         F         M
title
Close Shave, A (1995)                                   4.644444  4.473795
Wrong Trousers, The (1993)                              4.588235  4.478261
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)           4.572650  4.464589
Wallace & Gromit: The Best of Aardman Animation (1996)  4.563107  4.385075
Schindler's List (1993)                                 4.562602  4.491415

In [ ]:
mean_ratings["diff"] = mean_ratings["M"] - mean_ratings["F"]
mean_ratings

gender                                    F         M      diff
title
'burbs, The (1989)                 2.793478  2.962085  0.168607
10 Things I Hate About You (1999)  3.646552  3.311966 -0.334586
101 Dalmatians (1961)              3.791444  3.500000 -0.291444
101 Dalmatians (1996)              3.240000  2.911215 -0.328785
12 Angry Men (1957)                4.184397  4.328421  0.144024
...                                     ...       ...       ...
Young Guns (1988)                  3.371795  3.425620  0.053825
Young Guns II (1990)               2.934783  2.904025 -0.030758
Young Sherlock Holmes (1985)       3.514706  3.363344 -0.151362
Zero Effect (1998)                 3.864407  3.723140 -0.141266
eXistenZ (1999)                    3.098592  3.289086  0.190494

[1216 rows x 3 columns]

In [ ]:
sorted_by_diff = mean_ratings.sort_values("diff")
sorted_by_diff.head()

gender                            F         M      diff
title
Dirty Dancing (1987)       3.790378  2.959596 -0.830782
Jumpin' Jack Flash (1986)  3.254717  2.578358 -0.676359
Grease (1978)              3.975265  3.367041 -0.608224
Little Women (1994)        3.870588  3.321739 -0.548849
Steel Magnolias (1989)     3.901734  3.365957 -0.535777

In [ ]:
sorted_by_diff[::-1].head()

gender                                         F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Cable Guy, The (1996)                   2.250000  2.863787  0.613787

In [ ]:
rating_std_by_title = data.groupby("title")["rating"].std()
rating_std_by_title = rating_std_by_title.loc[active_titles]
rating_std_by_title.head()

title
'burbs, The (1989)                   1.107760
10 Things I Hate About You (1999)    0.989815
101 Dalmatians (1961)                0.982103
101 Dalmatians (1996)                1.098717
12 Angry Men (1957)                  0.812731
Name: rating, dtype: float64

In [ ]:
rating_std_by_title.sort_values(ascending=False)[:10]

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
Eyes Wide Shut (1999)                    1.259624
Evita (1996)                             1.253631
Billy Madison (1995)                     1.249970
Fear and Loathing in Las Vegas (1998)    1.246408
Bicentennial Man (1999)                  1.245533
Name: rating, dtype: float64

In [ ]:
movies["genres"].head()
movies["genres"].head().str.split("|")
movies["genre"] = movies.pop("genres").str.split("|")
movies.head()

0     Animation|Children's|Comedy
1    Adventure|Children's|Fantasy
2                  Comedy|Romance
3                    Comedy|Drama
4                          Comedy
Name: genres, dtype: object

0     [Animation, Children's, Comedy]
1    [Adventure, Children's, Fantasy]
2                   [Comedy, Romance]
3                     [Comedy, Drama]
4                            [Comedy]
Name: genres, dtype: object

,movie_id,title,genre
0,1,Toy Story (1995),"[Animation, Children's, Comedy]"
1,2,Jumanji (1995),"[Adventure, Children's, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [ ]:
movies_exploded = movies.explode("genre")
movies_exploded[:10]

      movie_id                            title       genre
1344      1365                  Ridicule (1996)       Drama
2637      2706              American Pie (1999)      Comedy
3598      3667                Rent-A-Cop (1988)      Action
3598      3667                Rent-A-Cop (1988)      Comedy
3615      3684  Fabulous Baker Boys, The (1989)       Drama
3615      3684  Fabulous Baker Boys, The (1989)     Romance
1812      1881         Quest for Camelot (1998)   Adventure
1812      1881         Quest for Camelot (1998)   Animation
1812      1881         Quest for Camelot (1998)  Children's
1812      1881         Quest for Camelot (1998)     Fantasy

In [ ]:
# @title **모든 장르를 컬럼으로하고 해당이 되면 0 아니면 1로 값을 입력하는 코드**

genres_one_hot = pd.get_dummies(movies_exploded['genre'], prefix='genre')
movies_with_genres = movies_exploded[['movie_id', 'title']].drop_duplicates().set_index('movie_id')

# Merge the one-hot encoded genres with movie_id and title
movies_genres_encoded = pd.merge(movies_exploded[['movie_id', 'title']], genres_one_hot, left_index=True, right_index=True)

# Group by movie_id and title, then sum the genre columns to handle movies with multiple genres
final_movies_genres = movies_genres_encoded.groupby(['movie_id', 'title']).sum().reset_index()

# Convert sums greater than 1 to 1 for true binary representation (though get_dummies + sum should result in 0 or 1 if genre is unique per row)
# In case a movie had the same genre listed multiple times, this step ensures it's still 1.
for col in final_movies_genres.columns:
    if col.startswith('genre_'):
        final_movies_genres[col] = (final_movies_genres[col] > 0).astype(int)

final_movies_genres.head()

,movie_id,title,genre_Action,genre_Adventure,genre_Animation,genre_Children's,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Fantasy,genre_Film-Noir,genre_Horror,genre_Musical,genre_Mystery,genre_Romance,genre_Sci-Fi,genre_Thriller,genre_War,genre_Western
0,9,Sudden Death (1995),1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,15,Cutthroat Island (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,18,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,33,Wings of Courage (1995),0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,71,Fair Game (1995),1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
ratings_with_genre = pd.merge(pd.merge(movies_exploded, ratings), users)
ratings_with_genre.iloc[0]
genre_ratings = (ratings_with_genre.groupby(["genre", "age"])
                 ["rating"].mean()
                 .unstack("age"))
genre_ratings[:10]

movie_id                 1365
title         Ridicule (1996)
genre                   Drama
user_id                    53
rating                      5
timestamp           977985605
gender                      M
age                        25
occupation                  0
zip                     96931
Name: 0, dtype: object

age,1,18,25,35,45,50,56
genre,,,,,,,
Action,3.488778,3.560880,3.609314,3.642322,3.661877,3.673228,3.643443
Adventure,3.494545,3.633867,3.654829,3.643646,3.626263,3.674617,3.698962
Animation,3.277108,3.467890,3.632727,3.705882,3.430894,3.547170,3.130435
Children's,2.932961,2.952880,3.001125,3.210811,3.071823,3.009346,2.885714
Comedy,3.339726,3.305200,3.396159,3.453784,3.510140,3.566148,3.553271
Crime,3.566038,3.189687,3.081152,3.332110,3.427419,3.604762,3.446429
Documentary,NaN,NaN,4.000000,3.428571,3.000000,3.000000,4.500000
Drama,3.926295,3.885337,3.851091,3.853600,3.879183,3.916006,3.974958
Fantasy,2.545455,2.666667,3.082569,3.511364,3.346939,3.500000,2.800000
Film-Noir,3.000000,3.333333,4.090909,3.476190,4.000000,4.304348,3.882353